name: Deploy Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.3'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          echo "PRIVATE_ENCRYPTOR_KEY=${{ secrets.PRIVATE_ENCRYPTOR_KEY }}" >> .env
          echo "IV_PRIVATE_ENCRYPTOR_KEY=${{ secrets.IV_PRIVATE_ENCRYPTOR_KEY }}" >> .env
          echo "PROD_URL=${{ secrets.PROD_URL }}" >> .env
          echo "DEV_URL=localhost" >> .env

      - name: Generate Envied Files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Upload to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/web/*"
          target: "/var/www/bincang-visual-web"
          strip_components: 2